# Generated by Django 4.1.3 on 2023-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jop_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('part time', 'part time')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
